[versions]
accompanistPermissions = "0.34.0"
agp = "8.9.0"
androidxJunit = "1.1.5"
androidxUiTestJunit4 = "<version>"
core = "1.6.1"
datastorePreferences = "1.1.7"
espressoCoreVersion = "3.5.1"
firebaseBom = "33.15.0"
fragmentKtx = "1.8.7"
coreKtx = "1.16.0"
googlePlayServicesLocation = "21.0.1"
googleServices = "4.4.2"
junit = "4.13.2"
junitVersion = "1.2.1"
espressoCore = "3.6.1"
kotlin = "2.0.21"
kotlinx-serialization = "1.6.0"
compose-compiler = "1.5.15"
kotlinxCoroutinesAndroid = "1.7.3"
kotlinxCoroutinesTest = "1.7.3"
kotlinxCoroutinesTestVersion = "1.6.4"
lifecycleRuntimeKtx = "2.9.0"
activityCompose = "1.10.1"
composeBom = "2024.09.00"
mockitoCore = "4.5.1"
mockitoKotlin = "4.0.0"
mockk = "1.13.10"
navigationCompose = "2.9.0"
navigationComposeVersion = "2.7.7"
maps = "18.1.0"
maps-compose = "2.11.4"
navigationTesting = "2.7.5"
playServicesLocation = "21.3.0"
robolectric = "4.9"
robolectricRobolectric = "4.10.3"
tensorflowLite = "2.4.0"
tensorflowLiteSupport = "0.4.0"
uiTestJunit4 = "1.8.2"
uiTestManifest = "<version>"
workRuntime = "2.10.1"
workRuntimeKtx = "2.10.1"
workTesting = "2.10.2"

[libraries]
accompanist-permissions = { module = "com.google.accompanist:accompanist-permissions", version.ref = "accompanistPermissions" }
androidx-core = { module = "androidx.test:core", version.ref = "core" }
androidx-datastore-preferences = { module = "androidx.datastore:datastore-preferences", version.ref = "datastorePreferences" }
androidx-espresso-core-v351 = { module = "androidx.test.espresso:espresso-core", version.ref = "espressoCoreVersion" }
androidx-foundation-permissions = { module = "androidx.compose.foundation:foundation-permissions" }
androidx-fragment-ktx = { module = "androidx.fragment:fragment-ktx", version.ref = "fragmentKtx" }
androidx-junit-v115 = { module = "androidx.test.ext:junit", version.ref = "androidxJunit" }
androidx-navigation-testing = { group = "androidx.navigation", name = "navigation-testing", version.ref = "navigationComposeVersion" }
androidx-navigation-testing-v275 = { module = "androidx.navigation:navigation-testing", version.ref = "navigationTesting" }
androidx-ui-test-junit4-vversion = { module = "androidx.compose.ui:ui-test-junit4", version.ref = "androidxUiTestJunit4" }
androidx-work-runtime = { module = "androidx.work:work-runtime", version.ref = "workRuntime" }
androidx-work-runtime-ktx = { module = "androidx.work:work-runtime-ktx", version.ref = "workRuntimeKtx" }
androidx-work-testing = { module = "androidx.work:work-testing", version.ref = "workTesting" }
firebase-analytics = { module = "com.google.firebase:firebase-analytics" }
firebase-bom = { module = "com.google.firebase:firebase-bom", version.ref = "firebaseBom" }
google-maps = { module = "com.google.android.gms:play-services-maps", version.ref = "maps" }
google-services = { module = "com.google.gms:google-services", version.ref = "googleServices" }
kotlinx-coroutines-android = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-android", version.ref = "kotlinxCoroutinesAndroid" }
kotlinx-coroutines-test = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-test", version.ref = "kotlinxCoroutinesTest" }
kotlinx-coroutines-test-v164 = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-test", version.ref = "kotlinxCoroutinesTestVersion" }
kotlinx-serialization-json = { module = "org.jetbrains.kotlinx:kotlinx-serialization-json", version.ref = "kotlinx-serialization" }
maps-compose = { module = "com.google.maps.android:maps-compose", version.ref = "maps-compose" }
androidx-compose-compiler = { group = "androidx.compose.compiler", name = "compiler", version.ref = "compose-compiler" }
androidx-core-ktx = { group = "androidx.core", name = "core-ktx", version.ref = "coreKtx" }
androidx-navigation-compose = { module = "androidx.navigation:navigation-compose", version.ref = "navigationCompose" }
junit = { group = "junit", name = "junit", version.ref = "junit" }
androidx-junit = { group = "androidx.test.ext", name = "junit", version.ref = "junitVersion" }
androidx-espresso-core = { group = "androidx.test.espresso", name = "espresso-core", version.ref = "espressoCore" }
androidx-lifecycle-runtime-ktx = { group = "androidx.lifecycle", name = "lifecycle-runtime-ktx", version.ref = "lifecycleRuntimeKtx" }
androidx-activity-compose = { group = "androidx.activity", name = "activity-compose", version.ref = "activityCompose" }
androidx-compose-bom = { group = "androidx.compose", name = "compose-bom", version.ref = "composeBom" }
androidx-ui = { group = "androidx.compose.ui", name = "ui" }
androidx-ui-graphics = { group = "androidx.compose.ui", name = "ui-graphics" }
androidx-ui-tooling = { group = "androidx.compose.ui", name = "ui-tooling" }
androidx-ui-tooling-preview = { group = "androidx.compose.ui", name = "ui-tooling-preview" }
androidx-ui-test-manifest = { group = "androidx.compose.ui", name = "ui-test-manifest" }
androidx-ui-test-junit4 = { group = "androidx.compose.ui", name = "ui-test-junit4" }
androidx-material3 = { group = "androidx.compose.material3", name = "material3" }
mockito-core = { module = "org.mockito:mockito-core", version.ref = "mockitoCore" }
mockito-kotlin = { module = "org.mockito.kotlin:mockito-kotlin", version.ref = "mockitoKotlin" }
mockk = { module = "io.mockk:mockk", version.ref = "mockk" }
navigation-testing = { module = "androidx.navigation:navigation-testing" }
play-services-location = { module = "com.google.android.gms:play-services-location", version.ref = "playServicesLocation" }
play-services-location-v2101 = { module = "com.google.android.gms:play-services-location", version.ref = "googlePlayServicesLocation" }
robolectric = { module = "org.robolectric:robolectric", version.ref = "robolectric" }
robolectric-v4103 = { module = "org.robolectric:robolectric", version.ref = "robolectricRobolectric" }
tensorflow-lite = { module = "org.tensorflow:tensorflow-lite", version.ref = "tensorflowLite" }
tensorflow-lite-support = { module = "org.tensorflow:tensorflow-lite-support", version.ref = "tensorflowLiteSupport" }
ui-test-junit4 = { module = "androidx.compose.ui:ui-test-junit4", version.ref = "uiTestJunit4" }
ui-test-manifest = { module = "androidx.compose.ui:ui-test-manifest", version.ref = "uiTestManifest" }

[plugins]
android-application = { id = "com.android.application", version.ref = "agp" }
kotlin-android = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }
kotlin-compose = { id = "org.jetbrains.kotlin.plugin.compose", version.ref = "kotlin" }
kotlin-serialization = { id = "org.jetbrains.kotlin.plugin.serialization", version.ref = "kotlin" }

